Mg 69 collections
SlovakNationalGallery/sbirky-moravska-galerie pull request #12
Opened 2024-04-24 22:57 UTC by rastislav-chynoransky

https://jira.sng.sk/browse/MG-69

2024-04-30 06:49 UTC, mayoforkovic commented on models/Collection.ts
> +  items: Item[] = []
Can you add zod schema parse? 
Example is in my last commits, Ill show you after standup.

2024-04-30 06:57 UTC, mayoforkovic commented on plugins/collections.ts
This should be state managment for detail of collection and not index of collections. You have it reversed.

2024-04-30 06:58 UTC, mayoforkovic requested changes
Good direction but lets discus how to optimize collections plugin or maybe reuse controls from filter plugin we have already.

2024-05-06 05:39 UTC, eronisko reviewed
I don't understand the need for plugin and injection (except it being consistent with previous code)

LGTM otherwise

2024-05-06 05:39 UTC, eronisko commented on plugins/collections.ts
> +})
Why is this a plugin and not just a plain composable?

2024-05-23 11:42 UTC, mayoforkovic approved these changes

2024-05-23 11:44 UTC, merged