MG-52: Skeleton component
SlovakNationalGallery/sbirky-moravska-galerie pull request #24
Opened 2024-06-12 17:08 UTC by mayoforkovic

- Updated `Item.vue` to include a new `Skeleton.vue` component for better loading experience
- Removed some redundant classes in `NuxtLink` within `Item.vue`
- Added conditional classes to handle opacity transitions based on the loaded state in `Skeleton.vue`
- Created a new file for the `Skeleton.vue` component with props for loaded state and aspect ratio

2024-06-13 15:42 UTC, rastislav-chynoransky requested changes

2024-06-13 15:42 UTC, rastislav-chynoransky commented on components/general/Skeleton.vue
> +        class="transition-opacity duration-500"
```suggestion
```
This is redundant as the animation is defined by keyframes

2024-06-13 15:42 UTC, rastislav-chynoransky commented on components/general/Skeleton.vue
> +    <div class="bg-gray-400 aspect-square" :style="{ aspectRatio: ratio }">
Currently the gray background is visible so that the image is no bigger than the viewport height. However, i'm not sure if scaling down of images is desired in the listing view. cc @mcudrnak ?

<img width="1289" alt="Screenshot 2024-06-13 at 17 38 30" src="https://github.com/SlovakNationalGallery/sbirky-moravska-galerie/assets/6841484/7ffcd1a0-8774-4696-93a5-dffa319949e5">

2024-06-13 15:42 UTC, rastislav-chynoransky commented on components/general/Skeleton.vue
> +        :class="{ 'opacity-0': !loaded, 'opacity-100': loaded }"
Seems redundant as well...

2024-06-13 15:42 UTC, rastislav-chynoransky commented on components/general/Skeleton.vue
> +  ratio: number | string
Why `string`?

2024-06-27 17:59 UTC, mayoforkovic commented on components/general/Skeleton.vue
> +        class="transition-opacity duration-500"
duration is set for opacity transition slot element and animation is on slot wrapper/parent

2024-06-27 18:37 UTC, mayoforkovic commented
skeleton is not wrapping image now, just overlaying it
and its also applied for images on detail

2024-07-01 20:12 UTC, rastislav-chynoransky commented on components/general/Skeleton.vue
> +    <div class="bg-gray-400 aspect-square" :style="{ aspectRatio: ratio }">
Now it's warping the image

<img width="1408" alt="Screenshot 2024-07-01 at 22 10 12" src="https://github.com/SlovakNationalGallery/sbirky-moravska-galerie/assets/6841484/ca21e67e-3998-4964-9318-66ab6ad9831d">

2024-07-02 17:29 UTC, mayoforkovic commented on components/general/Skeleton.vue
> +    <div class="bg-gray-400 aspect-square" :style="{ aspectRatio: ratio }">
I would prefer to keep it consistent, fixed pushed

2024-07-02 17:51 UTC, rastislav-chynoransky approved these changes

2024-07-03 07:22 UTC, merged